spring.application.name=tu-evento

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tu-evento
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate dialecto para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar las sentencias SQL en consola (opcional, útil para desarrollo)
spring.jpa.show-sql=true

# Crear y actualizar automáticamente las tablas (puedes cambiar a 'validate' en producción)
spring.jpa.hibernate.ddl-auto=update

# Zona horaria del servidor (opcional)
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Codificación de caracteres (opcional)
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'