@startuml Simple Service Class Diagram
left to right direction
skinparam nodesep 100
skinparam ranksep 50

together {
interface AccountActivationService {
}

class AccountActivationServiceImpl implements AccountActivationService {
}
interface AddressService {
}

class AddressServiceImpl implements AddressService {
}
interface CategoryEventService {
}
class CategoryEventServiceImpl implements CategoryEventService {
}
}
together {
interface CategoryService {
}

class CategoryServiceImpl implements CategoryService {
}
interface CityService {
}

class CityServiceImpl implements CityService {
}
interface DepartmentService {
}
class DepartmentServiceImpl implements DepartmentService {
}
}
together {
interface EventLayoutService {
}

class EventLayoutServiceImpl implements EventLayoutService {
}
interface EventRatingService {
}

class EventRatingServiceImpl implements EventRatingService {
}
interface EventService {
}
class EventServiceImpl implements EventService {
}
}
together {
interface LocationService {
}

class LocationServiceImpl implements LocationService {
}
interface LoginService {
}

class LoginServiceImpl implements LoginService {
}
interface NotificationService {
}
class NotificationServiceImpl implements NotificationService {
}
}
together {
interface NotificationUserService {
}

class NotificationUserServiceImpl implements NotificationUserService {
}
interface OrganizerPetitionService {
}

class OrganizerPetitionServiceImpl implements OrganizerPetitionService {
}
interface RecoverPasswordService {
}
class RecoverPasswordServiceImpl implements RecoverPasswordService {
}
}
together {
interface RegisterService {
}

class RegisterServiceImpl implements RegisterService {
}
interface SeatService {
}

class SeatServiceImpl implements SeatService {
}
interface SectionService {
}
class SectionServiceImpl implements SectionService {
}
}
together {
interface TicketService {
}

class TicketServiceImpl implements TicketService {
}
interface UserDetailsService {
}

class UserDetailsServiceImpl implements UserDetailsService {
}
interface UserService {
}
class UserServiceImpl implements UserService {
}
}

interface EventImgService {
}

interface SectionNameService {
}

class SectionNameServiceImpl implements SectionNameService {
}

@enduml